var numbers = [15, 45, 58, 49, 94, 73];
console.log(numbers);
console.log(numbers[4]);
var element = numbers[2];
console.log(element);
numbers[1] = 77;
numbers[5] = 512;
console.log(numbers);
var positionIndex = numbers.indexOf(94);
console.log(positionIndex); 
